---

- name: "Launch instance"
  ec2:
    key_name: "{{ keypair }}"
    group_id: "{{ security_group }}"
    instance_type: "{{ instance_type }}"
    image: "{{ image }}"
    wait: true
    region: "{{ region }}"
    vpc_subnet_id: subnet-cbae52af
    assign_public_ip: yes
  register: ec2
